version: '3.9'
services:
  mock-payment-service:
    build: ./mocks
    ports:
      - "8000:8000"

  automation-tests:
    build: .
    container_name: qa-automation
    depends_on:
      - mock-payment-service
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - ENV=qa
      - PAYMENT_URL=http://mock-payment-service:8000/process-payment
    entrypoint: ["behave"]
    command:
      [ # Add --tags=@ui or @api for tag based
        "--format", "behave_html_formatter:HTMLFormatter", "--outfile", "reports/html/report.html", "--format", "allure_behave.formatter:AllureFormatter", "--outfile", "reports/allure-results", "--junit", "--junit-directory", "reports/junit"
      ]

