default: qa

environments:
  qa:
    base_url: "https://fakestoreapi.com"
    db_host: "localhost"
    db_user: "qa_user"
    db_pass: "qa_password"

  staging:
    base_url: "https://staging.fakestoreapi.com"
    db_host: "staging-db"
    db_user: "staging_user"
    db_pass: "staging_password"
