name: CI - Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Run Tests with Docker Compose
        run: |
          docker compose down -v
          docker compose up --build -d   #Run in detached mode
          sleep 10                       #Give time for services to start
          docker compose logs automation-tests

      - name: Debug External API
        run: |
          docker compose exec automation-tests curl -I https://fakestoreapi.com/products || echo "External API not reachable"

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/html

      - name: Stop Containers
        if: always()
        run: docker compose down -v

  deploy-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: ./reports

      - name: Deploy report to GitHub Pages
        run: |
          cp ./reports/report.html index.html
          touch .nojekyll
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add index.html .nojekyll
          git commit -m "Update test report" || echo "No changes to commit"
          git push origin gh-pages